# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0, help_text=b'Valor do sensor')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='valor',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='codigo',
            field=models.IntegerField(default=0, help_text=b'Codigo do sensor', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sensorvalue',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor'),
        ),
    ]
