# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20160814_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='porta',
            field=models.TextField(default=0, help_text=b'Porta do sensor'),
        ),
    ]
