# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(default=b'', help_text=b'Codigo da parada')),
                ('logradouro', models.TextField(default=b'', help_text=b'Logradouro da parada')),
                ('bairro', models.TextField(default=b'', help_text=b'Bairro da parada')),
                ('cidade', models.TextField(default=b'', help_text=b'Cidade da parada')),
                ('latitude', models.TextField(default=b'', help_text=b'Latitude da parada')),
                ('longitude', models.TextField(default=b'', help_text=b'Longitude da parada')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='parada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rest_server.Parada'),
            preserve_default=False,
        ),
    ]
