# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_auto_20160814_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='parada',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
