# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0003_auto_20160814_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='id',
        ),
        migrations.AlterField(
            model_name='parada',
            name='codigo',
            field=models.TextField(default=b'', help_text=b'Codigo da parada', primary_key=True, serialize=False),
        ),
    ]
